spring.config.activate.on-profile=uat

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false

logging.level.root=WARN
logging.level.com.eazybytes.eazyschool.aspects = WARN
eazyschool.contact.pageSize=20



spring.datasource.url=jdbc:mysql://localhost:3306/jusvid?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Suhas@862004

spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.application.name=JusVid
